# Generated by Django 3.2.3 on 2024-01-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
